#ifndef STEP_H
#define STEP_H

namespace SGM
    {

    enum STEPTags
        {
        ADVANCED_BREP_SHAPE_REPRESENTATION,
        ADVANCED_FACE,
        APPLICATION_CONTEXT,
        APPLICATION_PROTOCOL_DEFINITION,
        AXIS2_PLACEMENT_3D,
        CARTESIAN_POINT,
        CIRCLE,
        CLOSED_SHELL,
        CYLINDRICAL_SURFACE,
        DIMENSIONAL_EXPONENTS,
        DIRECTION,
        EDGE_CURVE,
        EDGE_LOOP,
        FACE_OUTER_BOUND,
        LENGTH_MEASURE_WITH_UNIT,
        LINE,
        MANIFOLD_SOLID_BREP,
        MANIFOLD_SURFACE_SHAPE_REPRESENTATION,
        MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION,
        OPEN_SHELL,
        ORIENTED_EDGE,
        PLANE,
        PRODUCT,
        PRODUCT_CATEGORY,
        PRODUCT_CATEGORY_RELATIONSHIP,
        PRODUCT_CONTEXT,
        PRODUCT_DEFINITION,
        PRODUCT_DEFINITION_CONTEXT,
        PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE,
        PRODUCT_DEFINITION_SHAPE,
        PRODUCT_RELATED_PRODUCT_CATEGORY,
        SHAPE_DEFINITION_REPRESENTATION,
        SHELL_BASED_SURFACE_MODEL,
        SPHERICAL_SURFACE,
        UNCERTAINTY_MEASURE_WITH_UNIT,
        VECTOR,
        VERTEX_POINT,
        };

    } // End SGM namespace

#endif // STEP_H
